name: Populate ENV URL

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - Development
          - Testing
          - Migration
          - Acceptance
          - Production
      is_solution_upgrade_needed:
         description: 'Choose the environment'
         required: true
         type: choice
         options:
           - 'Yes'
           - 'No'
         
jobs:
  set-env-url:
    runs-on: ubuntu-latest
    steps:
      - name: Map Environment Name to URL and Authenticate
        shell: pwsh
        run: |
          $envName = "${{ github.event.inputs.environment }}"
          $environment_url = switch ($envName) {
            "Development" { "https://dev.crm4.dynamics.com" }
            "Testing"     { "https://tst.crm4.dynamics.com" }
            "Migration"   { "https://mig.crm4.dynamics.com" }
            "Acceptance"  { "https://acc.crm4.dynamics.com" }
            "Production"  { "https://prd.crm4.dynamics.com" }
            default       { throw "Unknown environment: $envName" }
          }
 
          Write-Host "Environment: $envName"
          Write-Host "Environment URL: $environment_url"
      - name: Import solutions with upgrade
        if: ${{ github.event.inputs.is_solution_upgrade_needed == 'Yes' }} 
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: "https://dev.crm4.dynamics.com"
        
         
          
          
