name: Populate ENV URL

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - Development
          - Testing
          - Migration
          - Acceptance
          - Production
  
      is_solution_upgrade_needed:
        description: 'Is solution upgrade needed?'
        required: true
        type: choice
        options:
          - 'Yes'
          - 'No'

jobs:
  set-env-url:
    runs-on: ubuntu-latest
    steps:
        - name: Set ENV URL
          run: |
            if [ "${{ github.event.inputs.environment }}" == "Development" ]; then
              echo "ENV_URL=https://dev.example.com" >> $GITHUB_ENV
            elif [ "${{ github.event.inputs.environment }}" == "Testing" ]; then
              echo "ENV_URL=https://test.example.com" >> $GITHUB_ENV
            elif [ "${{ github.event.inputs.environment }}" == "Migration" ]; then
              echo "ENV_URL=https://migration.example.com" >> $GITHUB_ENV
            elif [ "${{ github.event.inputs.environment }}" == "Acceptance" ]; then
              echo "ENV_URL=https://acceptance.example.com" >> $GITHUB_ENV
            elif [ "${{ github.event.inputs.environment }}" == "Production" ]; then
              echo "ENV_URL=https://prod.example.com" >> $GITHUB_ENV
            fi
        - name: Display ENV URL
          run: |
               echo "Environment URL is $ENV_URL"
               echo "Correct environment is ${{ env.ENV_URL }}"

