name: Populate ENV URL

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - Development
          - Testing
          - Migration
      is_solution_upgrade_needed:
        description: 'Is solution upgrade needed?'
        required: true
        type: choice
        options:
          - 'Yes'
          - 'No'

jobs:
  set-env-url:
    runs-on: ubuntu-latest
    steps:
      - name: Map Environment Name to URL and Authenticate
        shell: pwsh
        run: |
          $envName = "${{ github.event.inputs.environment }}"
          $environment_url = switch ($envName) {
            "Development" { "https://dev.crm4.dynamics.com" } >> $GITHUB_ENV
            "Testing"     { "https://tst.crm4.dynamics.com" } >> $GITHUB_ENV
            "Migration"   { "https://mig.crm4.dynamics.com" } >> $GITHUB_ENV
            "Acceptance"  { "https://acc.crm4.dynamics.com" } >> $GITHUB_ENV
            "Production"  { "https://prd.crm4.dynamics.com" } >> $GITHUB_ENV
            default       { throw "Unknown environment: $envName" }
          }
          Write-Host "Environment URL is $environment_url"
          Write-Host "Correct value is ${{ env.environment_url }}"

