name: Populate ENV URL

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - Development
          - Testing
          - Migration
      is_solution_upgrade_needed:
        description: 'Is solution upgrade needed?'
        required: true
        type: choice
        options:
          - 'Yes'
          - 'No'

jobs:
  set-env-url:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV URL
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Development" ]; then
            echo "ENV_URL=https://dev.example.com" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "Testing" ]; then
            echo "ENV_URL=https://test.example.com" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "Migration" ]; then
            echo "ENV_URL=https://prod.example.com" >> $GITHUB_ENV
          fi

      - name: Display ENV URL
        run: echo "Environment URL is $ENV_URL"
             echo ${{ env.ENV_URL }}

      - name: Import solutions with upgrade
        if: ${{ github.event.inputs.is_solution_upgrade_needed == 'Yes' }} 
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ env.ENV_URL }}
           echo ${{ env.ENV_URL }}
