on:
  workflow_dispatch:
jobs:
  convert-to-managed:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v4
      with:
        name: exportedSolution
        path: out/release/

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
         environment-url: ${{secrets.DESTINATION_URL}}
         app-id:  ${{ secrets.CLIENT_ID}}
         client-secret: ${{ secrets.PowerPlatformSPN }}
         tenant-id: ${{ secrets.TENANT_ID}}
        #environment-url: ${{env.PRODUCTION_ENVIRONMENT_URL}}
        #user-name: ${{env.USERNAME}}
        #password-secret: ${{ secrets.password }}
         solution-file: ${{ github.event.inputs.solution_release_folder}}/${{ github.event.inputs.solution_name }}.zip
         force-overwrite: true
         publish-changes: true
