name: export
on:
  workflow_dispatch:
   inputs:
     solution_names:
       description: 'solution names'
       required: true
       type: string
       default: '["solution1","solution2"]'
       
     source_env:
         description: 'source env names'
         type: choice
         required: true
         options:
           - Dev
           - Test
            - UAT
            - Prod
         default: 'Dev'
     solution_exported_folder:
         description: 'folder name for staging the exported solution *do not change*'
         required: true
         default: out/export
     solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: solutions
     managed-type:
         description: "Managed"
         type: choice
         required: true
         options:
            - true
            - false
         default: true
          
        
          
         
        
